select  * from customer limit 20


--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender;


--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT 
    customer_id,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount > (
    SELECT AVG(purchase_amount)
    FROM customer
);

--Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    AVG(review_rating) AS average_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_review_rating DESC
LIMIT 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT 
    shipping_type,
    AVG(purchase_amount) AS average_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


--Q5. Do subscribed customers spend more? Compare average spend and total revenue between
SELECT 
    subscription_status,
    ROUND(AVG(purchase_amount)::numeric, 2) AS average_spend,
    ROUND(SUM(purchase_amount)::numeric, 2) AS total_revenue
FROM customer
GROUP BY subscription_status;



--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
        / COUNT(*),
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;



--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT 
    customer_segment,
    COUNT(*) AS customer_count
FROM (
    SELECT 
        customer_id,
        CASE 
            WHEN previous_purchases = 0 THEN 'New'
            WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
) AS segments
GROUP BY customer_segment;


--Q8. What are the top 3 most purchased products within each category?
SELECT 
    category,
    item_purchased,
    purchase_count
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        RANK() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rank
    FROM customer
    GROUP BY category, item_purchased
) ranked_products
WHERE rank <= 3;


--09. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    subscription_status,
    COUNT(*) AS customer_count
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


--Q10. What is the revenue contribution of each age group?
SELECT 
    age_group,
    ROUND(SUM(purchase_amount)::numeric, 2) AS revenue_contribution
FROM (
    SELECT 
        purchase_amount,
        CASE 
            WHEN age BETWEEN 18 AND 25 THEN '18-25'
            WHEN age BETWEEN 26 AND 35 THEN '26-35'
            WHEN age BETWEEN 36 AND 45 THEN '36-45'
            WHEN age BETWEEN 46 AND 60 THEN '46-60'
            ELSE '60+'
        END AS age_group
    FROM customer
) AS grouped_data
GROUP BY age_group
ORDER BY revenue_contribution DESC;